package com.microservices.rest.webservices.restfulwebservices.user;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.List;

@ApiModel(description = "All details about the user.")
@Entity
public class User {

  @Id
  @GeneratedValue // this will indicate that this value will be generated by our
                  // database
  private Integer id;

  @Size(min = 2, message = "Name should have atleast 2 characters")
  @ApiModelProperty(notes = "Names should have atleast 2 characters")
  private String name;

  @Past
  @ApiModelProperty(notes = "Birth Date should be in the past")
  private Date birthDate;

  @OneToMany(mappedBy = "user")
  private List<Post> posts;

  protected User() {
  }

  public User(Integer id,
      @Size(min = 2, message = "Name should have atleast 2 characters") String name,
      @Past Date birthDate) {
    super();
    this.id = id;
    this.name = name;
    this.birthDate = birthDate;
  }

  @Override
  public String toString() {
    return "User{" + "id=" + id + ", name='" + name + '\'' + ", birthDate=" + birthDate + '}';
  }

  public List<Post> getPosts() {
    return posts;
  }

  public void setPosts(List<Post> posts) {
    this.posts = posts;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Date getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(Date birthDate) {
    this.birthDate = birthDate;
  }
}
